matrix:
  include:
  - dist: trusty
    language: node_js
    node_js:
    - node
    install:
    - npm ci
    script:
    - npm run-script ci
    deploy:
      provider: releases
      api_key:
        secure: "wuPg2tjYMue7HEGIpkd62AnnUx9qFZ8KIMlAA9auxbhDmG93pE2zOa8VIwVH2Qn/fR8qvNELbJsSkp83svnY3B5KP2976W9U4DckLzcrwxe9ndTrQsflP5ghZFns7qkg4hZXyGt/TNsB1WbngLteQJBHasbsg60R5xqngacM6go3d+LcUyyqw4FdzfGeOL/ZHmPCgcBUBfCvi30W8+ecQzzt+awaGyW6I2i6K86vUZalUI0cC70DLhTxqPcIIRRJUVKF/5Xiw8udfZ+Pl0zApm+UMdb7lnW+xIivnwbnbnHfmeEQBMfObULQ3ZtmoV/p8O9fMsxTpzJKzV0dKhfhoo9CgHqQX6oNmKTiFjApod2+J2oOZSsddWXI/3cRHZ1RD7GjeCZBi25m4jYIHGIUBA3FDdW7ib+9QqXdC17Li9BLe7KTvafd4zkhbhTVh9g/wkuNBAMkqzUUUhYFohZuap3U7ytgv/530lfNhjyNn5DZkXBZZuglK7hKvqGzWU8ozEAXPm17V+vS6jwQZdR6aPRJ2DOSvcd3u6bM1VQkR+tlsKcQ+hO7auqEFuuJPem5VPRmOdUwqFku3/Wa4OYHVYAf01Bbg5cgoOaquKQZGHxdqbPzdXUJX8TekMe2MboUuHT/zheEaryzGNyeyDcpNJuQUFNiiFWssJGgLS8ODvs="
      file_glob: true
      file: dist/*
      skip_cleanup: true
      on:
        branch: master
  - os: windows
    language: node_js
    node_js:
    - node
    install:
    - npm ci
    script:
    - npm run-script ci
  - os: osx
    language: node_js
    node_js:
    - node
    install:
    - npm ci
    script:
    - npm run-script ci
