name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm run-script ci
    - uses: actions/create-release@latest
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
      if: github.ref == 'refs/heads/master' && github.repository == 'jameswilddev/trash-kit'
