name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install chromium-browser
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.15"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm test
      - run: npm run-script ci
      - uses: actions/upload-artifact@v2-preview
        with:
          name: artifacts
          path: dist/*
